import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { ClerkProvider, auth } from "@clerk/nextjs";

import "./globals.css";
import Sidebar from "./Components/Sidebar/Sidebar";
import GlobalStyleProvider from "./providers/GlobalStyleProvider";
import ContextProvider from "./providers/ContextProvider";
import NextTopLoader from "nextjs-toploader";

// Инициализация шрифта Nunito с указанием весов и подмножеств.
const nunito = Nunito({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

// Метаданные для страницы.
export const metadata: Metadata = {
  title: "Задачи",
  description: "Generated by create next app",
};

// Основной компонент макета страницы.
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Получение идентификатора пользователя с использованием Clerk auth.
  const { userId } = auth();

  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          {/* Подключение стилей для иконок Font Awesome. */}
          <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
            integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
            crossOrigin="anonymous"
            referrerPolicy="no-referrer"
          />
        </head>
        <body className={nunito.className}>
          {/* Визуальный индикатор загрузки страницы. */}
          <NextTopLoader
            height={2}
            color="#27AE60"
            easing="cubic-bezier(0.53,0.21,0,1)"
          />
          <ContextProvider>
            <GlobalStyleProvider>
              {/* Компонент боковой панели (sidebar) для авторизованных пользователей. */}
              {userId && <Sidebar />}
              {/* Обертка для основного содержимого страницы. */}
              <div className="w-full">{children}</div>
            </GlobalStyleProvider>
          </ContextProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}